services:
  web:
    image: python:3.9
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0"
    environment:
      FLASK_APP: app.py

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: devops_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password