name: docker-ci-cd

on: 
  push:
    branches:
        - main

jobs:
  build:
      runs-on: ubuntu-latest
      services:
       docker:
        image: docker:20.10.24
      steps:
        - name: checar codigo
          uses: actions/checkout@v2

        - name: Configurar Docker
          run: |
            docker --version
            echo "Docker está configurado!"

        - name: rodar docker
          run: |
            docker run -d -p 3000:3000 node:latest
            docker ps

        - name: testar aplicacao
          run:  curl http://localhost:3000

        - name: fechar docker
          run: |
            docker stop $(docker ps -q)
            docker rm $(docker ps -aq)

            
        

            
